added method buyHouse
fichte-paulsen-lk/Polymony pull request #22
Opened 2020-02-17 12:06 UTC by Tippvehler

2020-02-17 12:09 UTC, markwitt1 requested changes
buuuh! voll schlecht!

2020-03-05 09:16 UTC, teknoalex commented on src/main/java/com/fichtepaulsen/polymony/Gamelogic/Game.java
> +        OwnableField[] save = (OwnableField[]) fields;
geht nicht!

2020-03-05 09:23 UTC, markwitt1 requested changes

2020-03-05 09:23 UTC, teknoalex commented on src/main/java/com/fichtepaulsen/polymony/Gamelogic/Game.java
> +        StreetField[] save = (StreetField[]) fields;
selbe hier

2020-03-05 09:23 UTC, teknoalex commented on src/main/java/com/fichtepaulsen/polymony/Gamelogic/Game.java
> +        Color save1 = save[0].getColor();
das ist nur die erste Straße

2020-03-05 09:23 UTC, teknoalex commented on src/main/java/com/fichtepaulsen/polymony/Gamelogic/Game.java
> +        StreetField[] save = (StreetField[]) getFieldsOwnedByPlayer(player);
hier nocchmal

2020-03-05 09:23 UTC, teknoalex commented on src/main/java/com/fichtepaulsen/polymony/Gamelogic/Game.java
> +        StreetField [] allFieldsSave= (StreetField [])fields;
nochmal

2020-03-05 09:23 UTC, teknoalex commented on src/main/java/com/fichtepaulsen/polymony/Gamelogic/Game.java
> +        OwnableField [] save=(OwnableField []) fields;
nochmal

2020-03-05 09:58 UTC, Tippvehler commented on src/main/java/com/fichtepaulsen/polymony/Gamelogic/Game.java
> +        Color save1 = save[0].getColor();
Doch es funktioniert. Erst denken, dann handeln.

2020-03-05 10:03 UTC, teknoalex commented on src/main/java/com/fichtepaulsen/polymony/Gamelogic/Game.java
> +        Color save1 = save[0].getColor();
### **_werden wir ja sehen_**!!!@Tippvehler

2020-03-09 12:08 UTC, markwitt1 requested changes
Check for NPEs due to unfilled HashMaps

2020-03-12 09:21 UTC, Broni07 commented on src/main/java/com/fichtepaulsen/polymony/Gamelogic/Game.java
> +        Color save1 = save[0].getColor();
**moin**

2020-03-12 09:26 UTC, Broni07 commented
Marvin was here!

2020-03-12 10:07 UTC, Amn3si4c approved these changes

2020-03-12 10:08 UTC, merged